apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nginx
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # rootpassword
  MYSQL_PASSWORD: bXlzcWxwYXNzd29yZA==  # mysqlpassword
